app/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings as setting
from core.dashboard.views import *

urlpatterns = [
    path('', include('core.homepage.urls')),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('security/', include('core.security.urls')),
    path('login/', include('core.login.urls')),
    path('user/', include('core.user.urls')),
    path('clinic/', include('core.clinic.urls')),
    path('reports/', include('core.reports.urls')),
]

if setting.DEBUG:
    urlpatterns += static(setting.MEDIA_URL, document_root=setting.MEDIA_ROOT)

app/core/clinic/crm/urls.py
from django.urls import path

from core.clinic.crm.views.clients.views import *
from core.clinic.crm.views.datemedical.admin.views import *
from core.clinic.crm.views.datemedical.client.views import *
from core.clinic.crm.views.exam.views import *
from core.clinic.crm.views.historialmedical.admin.views import HistorialMedicalAdminListView
from core.clinic.crm.views.historialmedical.client.views import HistorialMedicalClientListView

from core.clinic.crm.views.medicalparameters.views import *
from core.clinic.crm.views.sale.views import *

urlpatterns = [
    # clients
    path('clients/', ClientsListView.as_view(), name='clients_list'),
    path('clients/add/', ClientsCreateView.as_view(), name='clients_create'),
    path('clients/update/<int:pk>/', ClientsUpdateView.as_view(), name='clients_update'),
    path('clients/delete/<int:pk>/', ClientsDeleteView.as_view(), name='clients_delete'),
    # exam
    path('exam/', ExamListView.as_view(), name='exam_list'),
    path('exam/add/', ExamCreateView.as_view(), name='exam_create'),
    path('exam/update/<int:pk>/', ExamUpdateView.as_view(), name='exam_update'),
    path('exam/delete/<int:pk>/', ExamDeleteView.as_view(), name='exam_delete'),
    # medical parameters
    path('medical/parameters/', MedicalParametersListView.as_view(), name='medicalparameters_list'),
    path('medical/parameters/add/', MedicalParametersCreateView.as_view(), name='medicalparameters_create'),
    path('medical/parameters/update/<int:pk>/', MedicalParametersUpdateView.as_view(), name='medicalparameters_update'),
    path('medical/parameters/delete/<int:pk>/', MedicalParametersDeleteView.as_view(), name='medicalparameters_delete'),
    # datemedical/client
    path('date/medical/client/', DateMedicalClientListView.as_view(), name='datemedical_client_list'),
    path('date/medical/client/add/', DateMedicalClientCreateView.as_view(), name='datemedical_client_create'),
    path('date/medical/client/print/<int:pk>/', DateMedicalClientPrintView.as_view(), name='datemedical_client_print'),
    # datemedical/admin
    path('date/medical/admin/', DateMedicalAdminListView.as_view(), name='datemedical_admin_list'),
    path('date/medical/admin/add/', DateMedicalAdminCreateView.as_view(), name='datemedical_admin_create'),
    path('date/medical/admin/update/<int:pk>/', DateMedicalAdminUpdateView.as_view(), name='datemedical_admin_update'),
    path('date/medical/admin/delete/<int:pk>/', DateMedicalAdminDeleteView.as_view(), name='datemedical_admin_delete'),
    path('date/medical/admin/print/<int:pk>/', DateMedicalAdminPrintView.as_view(), name='datemedical_admin_print'),

    # sale
    path('sale/', SaleListView.as_view(), name='sale_list'),
    path('sale/add/', SaleCreateView.as_view(), name='sale_create'),
    path('sale/delete/<int:pk>/', SaleDeleteView.as_view(), name='sale_delete'),
    path('sale/print/invoice/<int:pk>/', SalePrintInvoice.as_view(), name='sale_print'),

    # historial/medical/client
    path('historial/medical/client/', HistorialMedicalClientListView.as_view(), name='historial_medical_client_list'),

    # historial/medical/admin
    path('historial/medical/admin/', HistorialMedicalAdminListView.as_view(), name='historial_medical_admin_list'),



]

app/core/clinic/crm/models.py
from django.db import models

from django.forms import model_to_dict

from core.clinic.choices import cite_status
from core.clinic.scm.models import Product,Provider
from core.user.models import User
from datetime import datetime, timedelta


class Exam(models.Model):
    name = models.CharField(verbose_name='Nombre', max_length=50, unique=True)

    def __str__(self):
        return self.name

    def toJSON(self):
        item = model_to_dict(self)
        return item

    class Meta:
        verbose_name = 'Examen'
        verbose_name_plural = 'Exámenes'
        ordering = ['-name']


class MedicalParameters(models.Model):
    name = models.CharField(verbose_name='Nombre', max_length=50, unique=True)

    def __str__(self):
        return self.name

    def toJSON(self):
        item = model_to_dict(self)
        return item

    class Meta:
        verbose_name = 'Parametro Medico'
        verbose_name_plural = 'Parametros Medicos'
        ordering = ['-id']


class DateMedical(models.Model):
    client = models.ForeignKey(User, on_delete=models.CASCADE)
    date_joined = models.DateField(default=datetime.now)
    lastperiod_date = models.DateField(default=datetime.now)
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)
    hour = models.TimeField(default=datetime.now)
    symptoms = models.CharField(max_length=5000)
    diagnosis = models.CharField(max_length=5000)
    treatment = models.CharField(max_length=5000)
    status = models.CharField(max_length=15, choices=cite_status, default=cite_status[0][0])
    # total = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)

    def __str__(self):
        return self.symptoms

    def get_weekday(self):
        weekday = 0
        lastperiod_date = self.lastperiod_date
        datenow = datetime.now().date()
        while lastperiod_date < datenow:
            if lastperiod_date.weekday() == 6:
                weekday += 1
            lastperiod_date = lastperiod_date + timedelta(days=1)
        return weekday

    def nro(self):
        return format(self.id, '06d')

    def toJSON(self):
        item = model_to_dict(self)
        item['client'] = self.client.toJSON()
        item['provider'] = self.provider.toJSON()
        item['date_joined'] = self.date_joined.strftime('%d-%m-%Y')
        item['lastperiod_date'] = self.lastperiod_date.strftime('%d-%m-%Y')
        item['hour'] = self.hour.strftime('%H:%M %p')
        item['status'] = {'id': self.status, 'name': self.get_status_display()}
        # item['total'] = format(self.total, '.2f')
        item['weekday'] = self.get_weekday()
        return item

    def calculate_invoice(self):
        subtotal = 0.00
        for d in self.datemedicalproducts_set.all():
            subtotal += float(d.price) * int(d.cant)
        # self.total = subtotal + self.total
        self.save()

    class Meta:
        verbose_name = 'Cita Médica'
        verbose_name_plural = 'Citas Médica'
        ordering = ['-id']


class DateMedicalProducts(models.Model):
    datemedical = models.ForeignKey(DateMedical, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cant = models.IntegerField(default=0)
    price = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    subtotal = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)

    def __str__(self):
        return self.product.name

    def toJSON(self):
        item = model_to_dict(self, exclude=['datemedical'])
        item['product'] = self.product.toJSON()
        item['price'] = format(self.price, '.2f')
        item['subtotal'] = format(self.subtotal, '.2f')
        return item

    class Meta:
        verbose_name = 'Cita Médica Producto'
        verbose_name_plural = 'Cita Médica Productos'
        default_permissions = ()
        ordering = ['-id']


class DateMedicalExam(models.Model):
    datemedical = models.ForeignKey(DateMedical, on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)

    def __str__(self):
        return self.exam.name

    def toJSON(self):
        item = model_to_dict(self, exclude=['datemedical'])
        item['exam'] = self.exam.toJSON()
        return item

    class Meta:
        verbose_name = 'Cita Médica Examen'
        verbose_name_plural = 'Cita Médica Examenes'
        default_permissions = ()
        ordering = ['-id']


class DateMedicalParameters(models.Model):
    datemedical = models.ForeignKey(DateMedical, on_delete=models.CASCADE)
    medicalparameters = models.ForeignKey(MedicalParameters, on_delete=models.CASCADE)
    valor = models.DecimalField(default=0.00, decimal_places=2, max_digits=9)

    def __str__(self):
        return self.medicalparameters.name

    def toJSON(self):
        item = model_to_dict(self, exclude=['datemedical'])
        item['medicalparameters'] = self.medicalparameters.toJSON()
        item['valor'] = format(self.valor, '.2f')
        return item

    class Meta:
        verbose_name = 'Cita Médica Parametro'
        verbose_name_plural = 'Cita Médica Parametros'
        default_permissions = ()
        ordering = ['-id']


class Sale(models.Model):
    client = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    date_joined = models.DateField(default=datetime.now)
    subtotal = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    iva = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return self.client.get_full_name()

    def nro(self):
        return format(self.id, '06d')

    def toJSON(self):
        item = model_to_dict(self, exclude=[''])
        item['nro'] = format(self.id, '06d')
        item['date_joined'] = self.date_joined.strftime('%Y-%m-%d')
        item['client'] = {} if self.client is None else self.client.toJSON()
        item['subtotal'] = format(self.subtotal, '.2f')
        item['iva'] = format(self.iva, '.2f')
        item['total'] = format(self.total, '.2f')
        return item

    def calculate_invoice(self):
        subtotal = 0.00
        for d in self.detsale_set.all():
            d.subtotal = float(d.price) * int(d.cant)
            d.save()
            subtotal += d.subtotal
        self.subtotal = subtotal
        self.iva = 0.12 * float(self.subtotal)
        self.total = float(self.subtotal) + float(self.iva)
        self.save()

    def delete(self, using=None, keep_parents=False):
        try:
            for i in self.detsale_set.all():
                i.product.stock += i.cant
                i.product.save()
                i.delete()
        except:
            pass
        super(Sale, self).delete()

    class Meta:
        verbose_name = 'Venta'
        verbose_name_plural = 'Ventas'
        default_permissions = ()
        permissions = (
            ('view_sale', 'Can view Ventas'),
            ('add_sale', 'Can add Ventas'),
            ('delete_sale', 'Can delete Ventas'),
        )
        ordering = ['-id']


class DetSale(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cant = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    dscto = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    subtotal = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return self.product.name

    def toJSON(self):
        item = model_to_dict(self, exclude=['sale'])
        item['product'] = self.product.toJSON()
        item['price'] = format(self.price, '.2f')
        item['dscto'] = format(self.dscto, '.2f')
        item['subtotal'] = format(self.subtotal, '.2f')
        return item

    class Meta:
        verbose_name = 'Det. Venta'
        verbose_name_plural = 'Det. Ventas'
        default_permissions = ()
        ordering = ['-id']

app/core/clinic/crm/views/exam/views.py
import json

from django.http import JsonResponse, HttpResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from core.clinic.crm.forms import Exam, ExamForm
from core.security.mixins import AccessModuleMixin, PermissionModuleMixin


class ExamListView(AccessModuleMixin, PermissionModuleMixin, ListView):
    model = Exam
    template_name = 'exam/list.html'
    permission_required = 'view_exam'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('exam_create')
        context['title'] = 'Listado de Exámenes'
        return context


class ExamCreateView(AccessModuleMixin, PermissionModuleMixin, CreateView):
    model = Exam
    template_name = 'exam/create.html'
    form_class = ExamForm
    success_url = reverse_lazy('exam_list')
    permission_required = 'add_exam'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def validate_data(self):
        data = {'valid': True}
        try:
            type = self.request.POST['type']
            obj = self.request.POST['obj'].strip()
            if type == 'name':
                if Exam.objects.filter(name__iexact=obj):
                    data['valid'] = False
        except:
            pass
        return JsonResponse(data)

    def post(self, request, *args, **kwargs):
        data = {}
        action = request.POST.get('action', None)
        try:
            if action == 'add':
                data = self.get_form().save()
            elif action == 'validate_data':
                return self.validate_data()
            else:
                data['error'] = 'No ha seleccionado ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return HttpResponse(json.dumps(data), content_type='application/json')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['list_url'] = self.success_url
        context['title'] = 'Nuevo registro de un Examen'
        context['action'] = 'add'
        return context


class ExamUpdateView(AccessModuleMixin, PermissionModuleMixin, UpdateView):
    model = Exam
    template_name = 'exam/create.html'
    form_class = ExamForm
    success_url = reverse_lazy('exam_list')
    permission_required = 'change_exam'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def validate_data(self):
        data = {'valid': True}
        try:
            type = self.request.POST['type']
            obj = self.request.POST['obj'].strip()
            id = self.get_object().id
            if type == 'name':
                if Exam.objects.filter(name__iexact=obj).exclude(id=id):
                    data['valid'] = False
        except:
            pass
        return JsonResponse(data)

    def post(self, request, *args, **kwargs):
        data = {}
        action = request.POST.get('action', None)
        try:
            if action == 'edit':
                data = self.get_form().save()
            elif action == 'validate_data':
                return self.validate_data()
            else:
                data['error'] = 'No ha seleccionado ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return HttpResponse(json.dumps(data), content_type='application/json')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['list_url'] = self.success_url
        context['title'] = 'Edición de un Examen'
        context['action'] = 'edit'
        return context


class ExamDeleteView(AccessModuleMixin, PermissionModuleMixin, DeleteView):
    model = Exam
    template_name = 'exam/delete.html'
    success_url = reverse_lazy('exam_list')
    permission_required = 'delete_exam'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.get_object().delete()
        except Exception as e:
            data['error'] = str(e)
        return HttpResponse(json.dumps(data), content_type='application/json')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Notificación de eliminación'
        context['list_url'] = self.success_url
        return context

app/core/clinic/crm/templates/datemedical/admin/delete.html
{% extends 'delete.html' %}

app/core/clinic/crm/templates/datemedical/admin/list.html
{% extends 'list.html' %}
{% load static %}
{% block head_list %}
    <script src="{% static 'lib/bootstrap-daterangepicker-3.0.5/spanish.js' %}"></script>
    <script src="{% static 'lib/bootstrap-daterangepicker-3.0.5/daterangepicker.js' %}"></script>
    <link rel="stylesheet" href="{% static 'lib/bootstrap-daterangepicker-3.0.5/daterangepicker.css' %}"/>
    <script src="{% static 'datemedical/admin/js/list.js' %}"></script>
{% endblock %}

{% block columns %}
    <tr>
        <th>Nro</th>
        <th>Cliente</th>
        <th>Fecha de registro</th>
        <th>Hora de registro</th>
        <th>Fecha de cita</th>
        <th>Semana</th>
        <th>Estado de Consulta</th>
        <th>Opciones</th>
    </tr>
{% endblock %}

{% block javascript_list %}
    <!-- Modal -->
    <div class="modal fade" id="myModalDetDateMedical" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">
                        <b><i class="fas fa-folder-open"></i> Detalle de la cita médica</b>
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#home">Datos de la cita</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#menu1">Parámetros Médicos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#menu2">Medicamentos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#menu3">Exámenes</a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane container-fluid active" id="home">
                            <br>
                            <table width="100%" class="table table-bordered" id="tblDateMedical">
                                <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Descripción</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                        <div class="tab-pane container-fluid fade" id="menu1">
                            <br>
                            <table width="100%" class="table table-bordered" id="tblMedicalParameters">
                                <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Valor</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                        <div class="tab-pane container-fluid fade" id="menu2">
                            <br>
                            <table width="100%" class="table table-bordered" id="tblMedicines">
                                <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Categoría</th>
                                    <th>Precio</th>
                                    <th>Cantidad</th>
                                    <th>Subtotal</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                        <div class="tab-pane container-fluid fade" id="menu3">
                            <br>
                            <table width="100%" class="table table-bordered" id="tblExams">
                                <thead>
                                <tr>
                                    <th>Nombre</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content_list_before %}
    <div class="row">
        <div class="col-lg-3">
            <div class="form-group">
                <label>Buscar por fecha de registro:</label>
                <div class="input-group">
                    <!-- {{ form.date_range }} -->
                    <span class="input-group-append">
                        <button type="button" class="btn btn-success btn-flat btnSearchAll">
                            <i class="fas fa-search"></i> Ver todas
                        </button>
                      </span>
                </div>
            </div>
        </div>
    </div>
    <hr>
{% endblock %}

app/core/clinic/crm/templates/datemedical/admin/ticket.html
<!DOCTYPE html>
{% load static %}
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<style>
    #header {
        padding-top: 10px;
        width: 50%;
        margin: 0;
        background-color: #000;
        font-size: 13px;
        color: #fff;
        font-weight: 700;
        text-align: center;
    }

    .img-invoice {
        width: 50px;
        text-align: center;
        margin: 0 auto;
    }

    .head {
        text-align: center;
        text-transform: uppercase;
        font-size: 12px;
        font-weight: bold;
    }

    #invoice thead tr th {
        text-align: left;
        border-bottom: 1px solid black;
        border-top: 1px solid black;
        padding-top: 4px;
    }

    #invoice thead tr {
        margin-bottom: 0;
        padding-bottom: 0;
    }

    #invoice tbody tr {
        padding: 0;
    }
</style>
<body>
<img src="{{ comp.get_image }}" class="img-invoice">
<p class="head">
    {{ comp.name|upper }}<br>
    {{ comp.proprietor }}<br>
    {{ comp.address|upper }}
</p>
<p>
    <b>FECHA DE REGISTRO:</b> {{ datemedical.date_joined }}<br>
    <b>FECHA DE ÚLTIMA REGLA:</b> {{ datemedical.lastperiod_date|upper }}<br>
    <b>SEMANA:</b> {{ datemedical.get_weekday|upper }}<br>
    <b>HORA DE REGISTRO:</b> {{ datemedical.hour|upper }}<br>
    <b>PACIENTE:</b> {{ datemedical.client.get_full_name|upper }}<br>
</p>
<hr>
<p>
    <b>Sintomas:</b><br>
    {{ datemedical.symptoms }}
</p>
<hr>
<p>
    <b>Diagnóstico:</b><br>
    {{ datemedical.diagnosis }}
</p>
<hr>
<p>
    <b>Tratamiento:</b><br>
    {{ datemedical.treatment }}
</p>
<p id="header">PARAMÉTROS</p>
<table id="invoice">
    <thead>
    <tr>
        <th style="width: 80%;">PARAMETRO</th>
        <th style="width: 20%;">VALOR</th>
    </tr>
    </thead>
    <tbody>
    {% for d in datemedical.datemedicalparameters_set.all %}
        <tr {% if forloop.first %}style="padding-top: 3px;" {% endif %}>
            <td>{{ d.medicalparameters.name }}</td>
            <td>{{ d.valor }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<p id="header">EXÁMENES</p>
<table id="invoice">
    <thead>
    <tr>
        <th style="width: 20%;">VALOR</th>
        <th style="width: 80%;">EXAMEN</th>
    </tr>
    </thead>
    <tbody>
    {% for d in datemedical.datemedicalexam_set.all %}
        <tr {% if forloop.first %}style="padding-top: 3px;" {% endif %}>
            <td>{{ forloop.counter }}</td>
            <td>{{ d.exam.name }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<p id="header">MEDICAMENTOS</p>
<table id="invoice">
    <thead>
    <tr>
        <th style="width: 60%;">PRODUCTO</th>
        <th style="width: 10%;">CANT</th>
        <th style="width: 15%;">P.UNITARIO</th>
        <th style="width: 15%;">SUBTOTAL</th>
    </tr>
    </thead>
    <tbody>
    {% for d in datemedical.datemedicalproducts_set.all %}
        <tr {% if forloop.first %}style="padding-top: 3px;" {% endif %}>
            <td>{{ d.product.name }}</td>
            <td style="text-align: center;">{{ d.cant }}</td>
            <td style="text-align: center;">{{ d.price }}</td>
            <td style="text-align: center;">{{ d.subtotal }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>