app/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings as setting
from core.dashboard.views import *

urlpatterns = [
    path('', include('core.homepage.urls')),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('security/', include('core.security.urls')),
    path('login/', include('core.login.urls')),
    path('user/', include('core.user.urls')),
    path('clinic/', include('core.clinic.urls')),
    path('reports/', include('core.reports.urls')),
]

if setting.DEBUG:
    urlpatterns += static(setting.MEDIA_URL, document_root=setting.MEDIA_ROOT)

app/core/homepage/urls.py
from django.urls import path
from django.views.generic import TemplateView

from core.homepage.views.services.views import *
from core.homepage.views.departments.views import *
from core.homepage.views.socialnetworks.views import *
from core.homepage.views.statistics.views import *
from core.homepage.views.mainpage.views import *
from core.homepage.views.freqquestions.views import *
from core.homepage.views.testimonials.views import *
from core.homepage.views.gallery.views import *
from core.homepage.views.team.views import *
from core.homepage.views.comments.views import *
from core.homepage.views.qualities.views import *
from core.homepage.views.news.views import *
from core.homepage.views.videos.views import *

urlpatterns = [
    # mainpage
    path('', MainPageIndexView.as_view(), name='index'),
    path('mainpage/update/', MainPageUpdateView.as_view(), name='main_update'),
    path('signin/', SignInView.as_view(), name='signin'),


    # services
    path('homepage/services/', ServicesListView.as_view(), name='services_list'),
    path('homepage/services/add/', ServicesCreateView.as_view(), name='services_create'),
    path('homepage/services/update/<int:pk>/', ServicesUpdateView.as_view(), name='services_update'),
    path('homepage/services/delete/<int:pk>/', ServicesDeleteView.as_view(), name='services_delete'),
    # departments
    path('homepage/departments/', DepartmentsListView.as_view(), name='departments_list'),
    path('homepage/departments/add/', DepartmentsCreateView.as_view(), name='departments_create'),
    path('homepage/departments/update/<int:pk>/', DepartmentsUpdateView.as_view(), name='departments_update'),
    path('homepage/departments/delete/<int:pk>/', DepartmentsDeleteView.as_view(), name='departments_delete'),
    # socialnetworks
    path('homepage/socialnetworks/', SocialNetworksListView.as_view(), name='socialnetworks_list'),
    path('homepage/socialnetworks/add/', SocialNetworksCreateView.as_view(), name='socialnetworks_create'),
    path('homepage/socialnetworks/update/<int:pk>/', SocialNetworksUpdateView.as_view(), name='socialnetworks_update'),
    path('homepage/socialnetworks/delete/<int:pk>/', SocialNetworksDeleteView.as_view(), name='socialnetworks_delete'),
    # statistics
    path('homepage/statistics/', StatisticsListView.as_view(), name='statistics_list'),
    path('homepage/statistics/add/', StatisticsCreateView.as_view(), name='statistics_create'),
    path('homepage/statistics/update/<int:pk>/', StatisticsUpdateView.as_view(), name='statistics_update'),
    path('homepage/statistics/delete/<int:pk>/', StatisticsDeleteView.as_view(), name='statistics_delete'),
    # freqquestions
    path('homepage/freqquestions/', FreqQuestionsListView.as_view(), name='freqquestions_list'),
    path('homepage/freqquestions/add/', FreqQuestionsCreateView.as_view(), name='freqquestions_create'),
    path('homepage/freqquestions/update/<int:pk>/', FreqQuestionsUpdateView.as_view(), name='freqquestions_update'),
    path('homepage/freqquestions/delete/<int:pk>/', FreqQuestionsDeleteView.as_view(), name='freqquestions_delete'),
    # testimonials
    path('homepage/testimonials/', TestimonialsListView.as_view(), name='testimonials_list'),
    path('homepage/testimonials/add/', TestimonialsCreateView.as_view(), name='testimonials_create'),
    path('homepage/testimonials/update/<int:pk>/', TestimonialsUpdateView.as_view(), name='testimonials_update'),
    path('homepage/testimonials/delete/<int:pk>/', TestimonialsDeleteView.as_view(), name='testimonials_delete'),
    # galery
    path('homepage/gallery/', GalleryListView.as_view(), name='gallery_list'),
    path('homepage/gallery/add/', GalleryCreateView.as_view(), name='gallery_create'),
    path('homepage/gallery/update/<int:pk>/', GalleryUpdateView.as_view(), name='gallery_update'),
    path('homepage/gallery/delete/<int:pk>/', GalleryDeleteView.as_view(), name='gallery_delete'),
    # team
    path('homepage/team/', TeamListView.as_view(), name='team_list'),
    path('homepage/team/add/', TeamCreateView.as_view(), name='team_create'),
    path('homepage/team/update/<int:pk>/', TeamUpdateView.as_view(), name='team_update'),
    path('homepage/team/delete/<int:pk>/', TeamDeleteView.as_view(), name='team_delete'),
    # qualities
    path('homepage/qualities/', QualitiesListView.as_view(), name='qualities_list'),
    path('homepage/qualities/add/', QualitiesCreateView.as_view(), name='qualities_create'),
    path('homepage/qualities/update/<int:pk>/', QualitiesUpdateView.as_view(), name='qualities_update'),
    path('homepage/qualities/delete/<int:pk>/', QualitiesDeleteView.as_view(), name='qualities_delete'),
    # comments
    path('homepage/comments/', CommentsListView.as_view(), name='comments_list'),
    path('homepage/comments/delete/<int:pk>/', CommentsDeleteView.as_view(), name='comments_delete'),
    #  videos
    path('homepage/videos/', VideosListView.as_view(), name='videos_list'),
    path('homepage/videos/add/', VideosCreateView.as_view(), name='videos_create'),
    path('homepage/videos/update/<int:pk>/', VideosUpdateView.as_view(), name='videos_update'),
    path('homepage/videos/delete/<int:pk>/', VideosDeleteView.as_view(), name='videos_delete'),
    #  news
    path('homepage/news/', NewsListView.as_view(), name='news_list'),
    path('homepage/news/add/', NewsCreateView.as_view(), name='news_create'),
    path('homepage/news/update/<int:pk>/', NewsUpdateView.as_view(), name='news_update'),
    path('homepage/news/delete/<int:pk>/', NewsDeleteView.as_view(), name='news_delete'),

    path(
        'embarazo/',
        TemplateView.as_view(
            template_name='mainpage/pages/inner-page2.html'
        ),
        name='embarazo'
    ),
    path(
        'about/',
        TemplateView.as_view(
            template_name='mainpage/pages/inner-page.html'
        ),
        name='about'
    ),
]

app/core/homepage/models.py
import os

from django.db import models
from django.forms import model_to_dict

from datetime import datetime

from config import settings


class Mainpage(models.Model):
    name = models.CharField(verbose_name='Nombre', max_length=50)
    proprietor = models.CharField(verbose_name='Propietario', max_length=100)
    desc = models.CharField(verbose_name='Descripción', max_length=2000, blank=True, null=True)
    with_us = models.CharField(verbose_name='¿Porque estar con nosotros?', max_length=2000, blank=True, null=True)
    mission = models.CharField(verbose_name='Misión', max_length=1000, blank=True, null=True)
    vision = models.CharField(verbose_name='Visión', max_length=1000, blank=True, null=True)
    about_us = models.CharField(verbose_name='Quienes Somos', max_length=1000, blank=True, null=True)
    icon_image = models.ImageField(verbose_name='Logo', upload_to='mainpage/%Y/%m/%d', null=True, blank=True)
    phone = models.CharField(verbose_name='Teléfono Convencional', max_length=9, unique=True, blank=True, null=True)
    mobile = models.CharField(verbose_name='Teléfono Celular', max_length=10, unique=True, blank=True, null=True)
    email = models.EmailField(verbose_name='Correo Electrónico', max_length=50, unique=True, blank=True, null=True)
    address = models.CharField(verbose_name='Dirección', max_length=255, blank=True, null=True)
    horary = models.CharField(verbose_name='Horario', max_length=50, blank=True, null=True)
    coordinates = models.CharField(verbose_name='Coordenadas', max_length=50, blank=True, null=True)
    about_youtube = models.CharField(verbose_name='Video de Youtube', max_length=250, blank=True, null=True)

    def __str__(self):
        return self.name

    def get_latitude(self):
        return self.coordinates.split(',')[0].replace(',', '.')

    def get_longitude(self):
        return self.coordinates.split(',')[1].replace(',', '.')

    def get_image(self):
        if self.icon_image:
            return '{}{}'.format(settings.MEDIA_URL, self.icon_image)
        return '{}{}'.format(settings.STATIC_URL, 'img/default/empty.png')

    class Meta:
        verbose_name = 'Página Principal'
        verbose_name_plural = 'Paginas Principales'
        default_permissions = ()
        permissions = (
            ('view_mainpage', 'Can view Página Principal'),
        )
        ordering = ['-id']


class Services(models.Model):
    name = models.CharField(max_length=150, verbose_name='Título')
    desc = models.CharField(max_length=500, null=True, blank=True, verbose_name='Descripción')
    image = models.ImageField(upload_to='services/%Y/%m/%d', verbose_name='Imagen', null=True, blank=True)
    link = models.CharField(max_length=150, verbose_name='ENLACE', null=True, blank=True)
    state = models.BooleanField(default=True, verbose_name='Estado')

    def __str__(self):
        return self.name

    def get_image(self):
        if self.image:
            return '{}{}'.format(settings.MEDIA_URL, self.image)
        return '{}{}'.format(settings.STATIC_URL, 'img/default/empty.png')

    def toJSON(self):
        item = model_to_dict(self)
        item['image'] = self.get_image()
        return item

    class Meta:
        verbose_name = 'Servicio'
        verbose_name_plural = 'Servicios'
        ordering = ['-id']


class Departments(models.Model):
    name = models.CharField(max_length=150, verbose_name='Título')
    title = models.CharField(max_length=150, verbose_name='Subtítulo')
    desc = models.CharField(max_length=500, null=True, blank=True, verbose_name='Descripción')
    image = models.ImageField(upload_to='departments/%Y/%m/%d', verbose_name='Imagen', null=True, blank=True)
    state = models.BooleanField(default=True, verbose_name='Estado')

    def __str__(self):
        return self.name

    def get_image(self):
        if self.image:
            return '{}{}'.format(settings.MEDIA_URL, self.image)
        return '{}{}'.format(settings.STATIC_URL, 'img/default/empty.png')

    def toJSON(self):
        item = model_to_dict(self)
        item['image'] = self.get_image()
        return item

    class Meta:
        verbose_name = 'Departmento'
        verbose_name_plural = 'Departmentos'
        ordering = ['-id']


class FreqQuestions(models.Model):
    question = models.CharField(max_length=500, verbose_name='Pregunta')
    answer = models.TextField(verbose_name='Respuesta')
    state = models.BooleanField(default=True, verbose_name='Estado')

    def __str__(self):
        return self.question

    class Meta:
        verbose_name = 'Preguntas Frecuente'
        verbose_name_plural = 'Preguntas Frecuentes'
        ordering = ['-id']


class Testimonials(models.Model):
    names = models.CharField(max_length=150, verbose_name='Nombre')
    job = models.CharField(max_length=150, verbose_name='Profesión')
    desc = models.CharField(max_length=5000, verbose_name='Descripción')
    image = models.ImageField(upload_to='testimonials/%Y/%m/%d', verbose_name='Imagen', null=True, blank=True)
    state = models.BooleanField(default=True, verbose_name='Estado')

    def __str__(self):
        return self.names

    def delete(self, using=None, keep_parents=False):
        try:
            os.remove(self.image.path)
        except:
            pass
        super(Testimonials, self).delete()

    def get_image(self):
        if self.image:
            return '{}{}'.format(settings.MEDIA_URL, self.image)
        return '{}{}'.format(settings.STATIC_URL, 'img/default/empty.png')

    def toJSON(self):
        item = model_to_dict(self)
        return item

    class Meta:
        verbose_name = 'Testimonios'
        verbose_name_plural = 'Testimonio'
        ordering = ['-id']


class Gallery(models.Model):
    date_joined = models.DateField(default=datetime.now)
    name = models.CharField(max_length=150, verbose_name='Nombre')
    desc = models.CharField(max_length=500, null=True, blank=True, verbose_name='Descripción')
    image = models.ImageField(upload_to='gallery/%Y/%m/%d', verbose_name='Imagen', null=True, blank=True)
    state = models.BooleanField(default=True, verbose_name='Estado')

    def __str__(self):
        return self.image.url

    def get_image(self):
        if self.image:
            return '{}{}'.format(settings.MEDIA_URL, self.image)
        return '{}{}'.format(settings.STATIC_URL, 'img/default/empty.png')

    def toJSON(self):
        item = model_to_dict(self)
        item['image'] = self.get_image()
        return item

    class Meta:
        verbose_name = 'Galería'
        verbose_name_plural = 'Galerias'
        ordering = ['-id']


class Comments(models.Model):
    names = models.CharField(max_length=100, verbose_name='Nombres')
    email = models.CharField(max_length=150, verbose_name='Email')
    mobile = models.CharField(max_length=15, verbose_name='Teléfono')
    message = models.CharField(max_length=2000, verbose_name='Mensaje')

    def __str__(self):
        return self.message

    class Meta:
        verbose_name = 'Comentario'
        verbose_name_plural = 'Comentarios'
        ordering = ['-id']


class SocialNetworks(models.Model):
    css = models.CharField(max_length=50, verbose_name='Nombre de la clase css')
    icon = models.CharField(max_length=100, verbose_name='Icono font-awesome')
    url = models.CharField(max_length=150, verbose_name='Enlace')
    state = models.BooleanField(default=True, verbose_name='Estado')

    def __str__(self):
        return self.css

    def toJSON(self):
        item = model_to_dict(self)
        return item

    def get_icon(self):
        if self.icon:
            return self.icon
        return 'fa fa-times'

    class Meta:
        verbose_name = 'Red Social'
        verbose_name_plural = 'Redes Sociales'
        ordering = ['id']


class Statistics(models.Model):
    name = models.CharField(max_length=150, null=True, blank=True, verbose_name='Nombre')
    image = models.ImageField(upload_to='services/%Y/%m/%d', verbose_name='Imagen', null=True, blank=True)
    cant = models.IntegerField(default=0, verbose_name='Cantidad')
    state = models.BooleanField(default=True, verbose_name='Estado')

    def __str__(self):
        return self.name

    def get_image(self):
        if self.image:
            return '{}{}'.format(settings.MEDIA_URL, self.image)
        return '{}{}'.format(settings.STATIC_URL, 'img/default/empty.png')

    def toJSON(self):
        item = model_to_dict(self)
        item['image'] = self.get_image()
        return item

    class Meta:
        verbose_name = 'Estadística'
        verbose_name_plural = 'Estadísticas'
        ordering = ['-id']


class Team(models.Model):
    names = models.CharField(max_length=150, verbose_name='Nombre')
    phrase = models.CharField(max_length=5000, verbose_name='Frase')
    job = models.CharField(max_length=150, verbose_name='Profesión')
    image = models.ImageField(upload_to='team/%Y/%m/%d', verbose_name='Imagen', null=True, blank=True)
    desc = models.CharField(max_length=5000, null=True, blank=True, verbose_name='Descripción')
    state = models.BooleanField(default=True, verbose_name='Estado')

    def __str__(self):
        return self.names

    def toJSON(self):
        item = model_to_dict(self)
        return item

    def delete(self, using=None, keep_parents=False):
        try:
            os.remove(self.image.path)
        except:
            pass
        super(Team, self).delete()

    def get_image(self):
        if self.image:
            return '{}{}'.format(settings.MEDIA_URL, self.image)
        return '{}{}'.format(settings.STATIC_URL, 'img/default/empty.png')

    def short_name(self):
        names = self.names.split(' ')
        if len(names) == 4:
            return '{} {}'.format(names[0], names[3])
        return self.names

    class Meta:
        verbose_name = 'Equipo de Trabajo'
        verbose_name_plural = 'Equipos de Trabajo'
        ordering = ['-id']


class TeamSocialNet(models.Model):

app/core/homepage/templates/team/create.html
{% extends 'form.html' %}
{% load static %}
{% load widget_tweaks %}
{% block head_form %}
    <script src="{% static 'team/js/form.js' %}"></script>
{% endblock %}

{% block content %}
    <form class="form" method="post" action="." enctype="multipart/form-data" id="frmForm"
          data-url="{% url 'team_list' %}">
        <div class="card {{ dshboard.card }}">
            <div class="card-header">
                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i class="fas fa-plus"></i>
                    {% else %}
                        <i class="fas fa-edit"></i>
                    {% endif %}
                    {{ title }}
                </h3>
                <div class="card-tools">
                    <small>Su último acceso al sistema fue el {{ request.user.last_login }}</small>
                </div>
            </div>
            <div class="card-body" style="display: block;">
                <div class="container-fluid">
                    <input type="hidden" name="action" id="action" value="{{ action }}">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Nombres:</label>
                                {{ form.names }}
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Cargo:</label>
                                {{ form.job }}
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Estado:</label><br>
                                {{ form.state }}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label>Frase:</label>
                            {{ form.phrase }}
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label>Descripción:</label>
                            {{ form.desc }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Imagen:</label>
                                {{ form.image|add_class:'form-control'|attr:'autocomplete:off' }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <hr>
                            <a class="btn btn-success btn-sm btn-flat btnAdd">
                                <i class="fa fa-plus"></i> Agregar
                            </a>
                            <a class="btn btn-danger btn-sm btn-flat btnRemoveAll">
                                <i class="fa fa-trash"></i> Eliminar todo
                            </a>
                            <hr>
                            <table width="100%" class="table table-bordered" id="tblSocialNet">
                                <thead>
                                <tr>
                                    <th style="width: 5%;" class="text-center">Nro</th>
                                    <th style="width: 25%;">Nombre</th>
                                    <th style="width: 20%;">Icono</th>
                                    <th style="width: 35%;">Enlace</th>
                                    <th style="width: 15%;" class="text-center">
                                        <i class="fa fa-wrench"></i>
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Guardar registro
                </button>
                <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
    <script type="application/javascript">
        team.details.socialnet = {{ social|safe }};
        team.list();
    </script>
{% endblock %}

app/core/homepage/templates/team/delete.html
{% extends 'delete.html' %}

app/core/homepage/templates/team/list.html
{% extends 'list.html' %}

{% block columns %}
    <th class="text-center">Nro</th>
    <th>Nombres</th>
    <th>Cargo</th>
    <th>Imagen</th>
    <th>Redes Sociales</th>
    <th>Estado</th>
    <th class="text-center"><i class="fa fa-wrench"></i></th>
{% endblock %}

{% block rows %}
    {% for i in object_list %}
        <tr>
            <td>{{ i.id }}</td>
            <td>{{ i.names }}</td>
            <td>{{ i.job }}</td>
            <td class="text-center">
                <img src="{{ i.get_image }}" class="img-fluid d-block mx-auto" style="width: 20px; height: 20px;">
            </td>
            <td class="text-center">
                {% for s in i.teamsocialnet_set.all %}
                    <span class="badge badge-secondary"><i class="{{ s.icon }}"></i></span>
                {% endfor %}
            </td>
            <td class="text-center">
                {% if i.state %}
                    <span class="badge badge-success">Activo</span>
                {% else %}
                    <span class="badge badge-danger">Inactivo</span>
                {% endif %}
            </td>
            <td class="text-center">
                <a href="{% url 'team_update' i.id %}" data-toggle="tooltip" title="Editar registro"
                   class="btn btn-warning btn-xs btn-flat">
                    <i class="fas fa-edit"></i>
                </a>
                <a href="{% url 'team_delete' i.id %}" rel="delete" data-toggle="tooltip" title="Eliminar registro"
                   class="btn btn-danger btn-xs btn-flat">
                    <i class="fas fa-trash"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
{% endblock %}